import { describe, expect, test } from "bun:test"
import { dirname, join } from "node:path"
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"

const SCRIPT = join(import.meta.dir, "../scripts/check-tests.ts")

const write = (root: string, path: string, text: string) => {
  mkdirSync(dirname(join(root, path)), { recursive: true })
  writeFileSync(join(root, path), text)
}

const run = async (root: string, args: string[] = []) => {
  const proc = Bun.spawn(["bun", SCRIPT, ...args], { cwd: root, stdout: "pipe", stderr: "pipe" })
  const [code, out, err] = await Promise.all([
    proc.exited,
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
  ])
  return { code, out, err }
}

const git = async (root: string, ...args: string[]) => {
  const proc = Bun.spawn(["git", ...args], { cwd: root, stdout: "ignore", stderr: "pipe" })
  const [code, err] = await Promise.all([proc.exited, new Response(proc.stderr).text()])
  expect(code, err).toBe(0)
}

describe("check-tests", () => {
  test("reports high-confidence violations as raw path:line diagnostics", async () => {
    const root = mkdtempSync(join(tmpdir(), "herm-check-tests-"))
    try {
      write(root, "src/live.ts", "export const live = true\n")
      write(root, "test/bad.test.ts", [
        'import { expect, test } from "bun:test"',
        'import { readFileSync } from "node:fs"',
        'const t = { frame: () => "" }',
        'test.only("focus", () => expect(true).toBe(true))',
        'test("log", () => console.log(t.frame()))',
        'test("source", () => readFileSync(new URL("../src/live.ts", import.meta.url), "utf8"))',
        'test("wait", async () => until(t, () => true))',
        'test("frame", () => expect(t.frame()).toBeTruthy())',
        'test("same", () => expect(count(s)).toBe(count(s)))',
      ].join("\n"))

      const got = await run(root)
      expect(got.code).toBe(0)
      expect(got.out).toBe("")
      const diagnostics = [
        "test/bad.test.ts:4: focused tests are not allowed",
        "test/bad.test.ts:5: console.log-only test has no assertion",
        "test/bad.test.ts:6: test reads production TypeScript source",
        "test/bad.test.ts:7: until predicate is unconditionally true",
        "test/bad.test.ts:8: frame truthiness is not an assertion",
        "test/bad.test.ts:9: assertion compares an expression with itself",
      ]
      expect(got.err.trim().split("\n")).toEqual(diagnostics)

      const strict = await run(root, ["--strict"])
      expect(strict.code).toBe(1)
      expect(strict.out).toBe("")
      expect(strict.err.trim().split("\n")).toEqual(diagnostics)
    } finally {
      rmSync(root, { recursive: true, force: true })
    }
  })

  test("accepts protocol, race, meaningful wait, generated artifact, and fixture cases", async () => {
    const root = mkdtempSync(join(tmpdir(), "herm-check-tests-good-"))
    try {
      write(root, "src/schema.ts", "// Generated by scripts/gen-schema.ts — do not edit by hand.\nexport const schema = {}\n")
      write(root, "test/good.test.ts", [
        'import { expect, test } from "bun:test"',
        'import { readFileSync } from "node:fs"',
        'const fixture = `test.only("x", () => console.log("x")); until(t, () => true)`',
        '// test.only("x", () => expect(frame()).toBeTruthy())',
        'const packet = () => "\\u001b[?25l"',
        'test("protocol", () => expect(packet()).toBe("\\u001b[?25l"))',
        'test("race", async () => {',
        '  let release!: () => void',
        '  const gate = new Promise<void>(resolve => { release = resolve })',
        '  release()',
        '  await gate',
        '  expect(fixture.length).toBeGreaterThan(0)',
        '})',
        'test("wait", async () => until(t, () => t.frame().includes("Ready")))',
        'test("assert wait", async () => until(t, () => { expect(t.frame()).toContain("Ready"); return true }))',
        'test("log assertion", () => { console.log(packet()); expect(packet()).toStartWith("\\u001b") })',
        'test("generated", () => expect(readFileSync(new URL("../src/schema.ts", import.meta.url), "utf8")).toContain("schema"))',
      ].join("\n"))

      const got = await run(root)
      expect(got).toEqual({ code: 0, out: "", err: "" })
    } finally {
      rmSync(root, { recursive: true, force: true })
    }
  })

  test("changed mode requires a base and enforces only changed test files", async () => {
    const root = mkdtempSync(join(tmpdir(), "herm-check-tests-git-"))
    try {
      await git(root, "init", "-q", "-b", "main")
      write(root, "test/old.test.ts", 'test.only("baseline", () => {})\n')
      await git(root, "add", "test/old.test.ts")
      await git(root, "-c", "user.name=t", "-c", "user.email=t@t", "commit", "-qm", "base")
      write(root, "test/new.test.ts", 'test.only("changed", () => {})\n')
      write(root, "src/new.test.ts", 'test.only("changed source test", () => {})\n')

      const missing = await run(root, ["--changed"])
      expect(missing.code).toBe(2)
      expect(missing.err).toBe("check-tests: --changed requires an explicit git diff base\n")

      const got = await run(root, ["--changed", "HEAD"])
      expect(got.code).toBe(1)
      expect(got.err).toBe([
        "src/new.test.ts:1: focused tests are not allowed",
        "test/new.test.ts:1: focused tests are not allowed",
        "",
      ].join("\n"))
    } finally {
      rmSync(root, { recursive: true, force: true })
    }
  })
})
