#!/usr/bin/env bun
import ts from "typescript"
import { dirname, isAbsolute, resolve } from "node:path"

type Hit = { path: string; line: number; text: string }
type Pair = { got: ts.Expression; want: ts.Expression }

const decoder = new TextDecoder()
const tests = new Set(["test", "it"])
const scopes = new Set(["test", "it", "describe"])
const matchers = new Set(["toBe", "toEqual", "toStrictEqual"])

const unwrap = (node: ts.Expression): ts.Expression => {
  if (ts.isParenthesizedExpression(node) || ts.isAsExpression(node) || ts.isNonNullExpression(node) || ts.isTypeAssertionExpression(node))
    return unwrap(node.expression)
  return node
}

const base = (node: ts.Expression): string | undefined => {
  const expr = unwrap(node)
  if (ts.isIdentifier(expr)) return expr.text
  if (ts.isPropertyAccessExpression(expr)) return base(expr.expression)
  if (ts.isCallExpression(expr)) return base(expr.expression)
}

const has = (node: ts.Node, pick: (child: ts.Node) => boolean): boolean => {
  if (pick(node)) return true
  return node.getChildren().some(child => has(child, pick))
}

const log = (node: ts.Node) => ts.isCallExpression(node)
  && ts.isPropertyAccessExpression(node.expression)
  && ts.isIdentifier(node.expression.expression)
  && node.expression.expression.text === "console"
  && node.expression.name.text === "log"

const assertion = (node: ts.Node) => {
  if (ts.isThrowStatement(node)) return true
  if (!ts.isCallExpression(node)) return false
  return base(node.expression) === "expect" || base(node.expression) === "assert"
}

const literal = (node: ts.Expression) => {
  const expr = unwrap(node)
  return ts.isStringLiteralLike(expr)
    || ts.isNumericLiteral(expr)
    || expr.kind === ts.SyntaxKind.TrueKeyword
    || expr.kind === ts.SyntaxKind.FalseKeyword
    || expr.kind === ts.SyntaxKind.NullKeyword
}

const matcher = (node: ts.CallExpression): Pair | undefined => {
  if (!ts.isPropertyAccessExpression(node.expression) || !matchers.has(node.expression.name.text) || node.arguments.length !== 1)
    return
  const call = unwrap(node.expression.expression)
  if (!ts.isCallExpression(call) || base(call.expression) !== "expect" || call.arguments.length !== 1) return
  return { got: call.arguments[0], want: node.arguments[0] }
}

const truthy = (node: ts.CallExpression) => {
  if (!ts.isPropertyAccessExpression(node.expression) || node.expression.name.text !== "toBeTruthy") return false
  const call = unwrap(node.expression.expression)
  if (!ts.isCallExpression(call) || base(call.expression) !== "expect" || call.arguments.length !== 1) return false
  const got = unwrap(call.arguments[0])
  if (!ts.isCallExpression(got)) return false
  const fn = unwrap(got.expression)
  return ts.isIdentifier(fn) ? fn.text === "frame" : ts.isPropertyAccessExpression(fn) && fn.name.text === "frame"
}

const always = (node: ts.Expression) => {
  const fn = unwrap(node)
  if (!ts.isArrowFunction(fn) && !ts.isFunctionExpression(fn)) return false
  if (has(fn.body, assertion)) return false
  if (!ts.isBlock(fn.body)) return unwrap(fn.body).kind === ts.SyntaxKind.TrueKeyword
  return fn.body.statements.length > 0 && fn.body.statements.every(statement =>
    ts.isReturnStatement(statement) && statement.expression !== undefined
      && unwrap(statement.expression).kind === ts.SyntaxKind.TrueKeyword)
}

const meta = (node: ts.Expression) => ts.isPropertyAccessExpression(node)
  && ts.isMetaProperty(node.expression)
  && node.expression.keywordToken === ts.SyntaxKind.ImportKeyword
  && node.name.text === "dir"

const path = (node: ts.Expression, file: string, root: string): string | undefined => {
  const expr = unwrap(node)
  if (ts.isStringLiteralLike(expr)) return expr.text
  if (meta(expr)) return dirname(resolve(root, file))
  if (ts.isNewExpression(expr) && ts.isIdentifier(expr.expression) && expr.expression.text === "URL" && expr.arguments?.[0]) {
    const value = path(expr.arguments[0], file, root)
    return value === undefined ? undefined : resolve(dirname(resolve(root, file)), value)
  }
  if (!ts.isCallExpression(expr) || !ts.isIdentifier(expr.expression) || !["join", "resolve"].includes(expr.expression.text)) return
  const parts = expr.arguments.map(arg => path(arg, file, root))
  if (parts.some(part => part === undefined)) return
  return resolve(...parts.filter((part): part is string => part !== undefined))
}

const production = (path: string) => /(?:^|\/)src\/.*\.tsx?$/.test(path.replaceAll("\\", "/"))

const generated = async (root: string, file: string, path: string) => {
  const paths = isAbsolute(path)
    ? [path]
    : [resolve(root, path), resolve(dirname(resolve(root, file)), path)]
  for (const path of paths) {
    const file = Bun.file(path)
    if (!await file.exists()) continue
    const head = (await file.text()).slice(0, 512)
    if (/\bGenerated by\b|@generated\b/i.test(head)) return true
  }
  return false
}

const scan = async (root: string, file: string): Promise<Hit[]> => {
  const text = await Bun.file(resolve(root, file)).text()
  const source = ts.createSourceFile(file, text, ts.ScriptTarget.Latest, true,
    file.endsWith("x") ? ts.ScriptKind.TSX : ts.ScriptKind.TS)
  const reads = new Set<string>()
  const spaces = new Set<string>()
  const hits: Hit[] = []
  const pending: { node: ts.Node; path: string }[] = []

  source.statements.filter(ts.isImportDeclaration).forEach(statement => {
    if (!ts.isStringLiteral(statement.moduleSpecifier) || !/^(node:)?fs(?:\/promises)?$/.test(statement.moduleSpecifier.text)) return
    const clause = statement.importClause
    if (clause?.namedBindings && ts.isNamedImports(clause.namedBindings))
      clause.namedBindings.elements.forEach(item => {
        if (["readFile", "readFileSync"].includes(item.propertyName?.text ?? item.name.text)) reads.add(item.name.text)
      })
    if (clause?.namedBindings && ts.isNamespaceImport(clause.namedBindings)) spaces.add(clause.namedBindings.name.text)
  })

  const add = (node: ts.Node, text: string) => hits.push({
    path: file,
    line: source.getLineAndCharacterOfPosition(node.getStart(source)).line + 1,
    text,
  })

  const visit = (node: ts.Node) => {
    if (ts.isCallExpression(node)) {
      if (ts.isPropertyAccessExpression(node.expression)
        && node.expression.name.text === "only"
        && scopes.has(name(node.expression.expression)))
        add(node, "focused tests are not allowed")

      if (tests.has(name(node.expression))) {
        const fn = [...node.arguments].reverse().find((arg): arg is ts.ArrowFunction | ts.FunctionExpression =>
          ts.isArrowFunction(arg) || ts.isFunctionExpression(arg))
        if (fn && has(fn.body, log) && !has(fn.body, assertion)) {
          const first = find(fn.body, log)
          if (first) add(first, "console.log-only test has no assertion")
        }
      }

      if (name(node.expression) === "until" && node.arguments.some(always))
        add(node, "until predicate is unconditionally true")

      if (truthy(node)) add(node, "frame truthiness is not an assertion")

      const pair = matcher(node)
      if (pair && !literal(pair.got) && !literal(pair.want)
        && unwrap(pair.got).getText(source) === unwrap(pair.want).getText(source))
        add(node, "assertion compares an expression with itself")

      const expr = unwrap(node.expression)
      const direct = ts.isIdentifier(expr) && reads.has(expr.text)
        || ts.isPropertyAccessExpression(expr) && ts.isIdentifier(expr.expression)
          && spaces.has(expr.expression.text) && ["readFile", "readFileSync"].includes(expr.name.text)
        || ts.isPropertyAccessExpression(expr) && ts.isIdentifier(expr.expression)
          && expr.expression.text === "Bun" && expr.name.text === "file"
      if (direct && node.arguments[0]) {
        const value = path(node.arguments[0], file, root)
        if (value !== undefined && production(value)) pending.push({ node, path: value })
      }
    }
    ts.forEachChild(node, visit)
  }

  const name = (node: ts.Expression) => base(node) ?? ""
  const find = (node: ts.Node, pick: (child: ts.Node) => boolean): ts.Node | undefined => {
    if (pick(node)) return node
    for (const child of node.getChildren()) {
      const got = find(child, pick)
      if (got) return got
    }
  }

  visit(source)
  for (const read of pending)
    if (!await generated(root, file, read.path)) add(read.node, "test reads production TypeScript source")

  return hits
}

const full = (root: string) => ["test/**/*.test.ts", "test/**/*.test.tsx", "src/**/*.test.ts", "src/**/*.test.tsx"]
  .flatMap(pattern => [...new Bun.Glob(pattern).scanSync({ cwd: root, onlyFiles: true })])
  .sort()

const changed = (root: string, base: string) => {
  const ref = Bun.spawnSync(["git", "rev-parse", "--verify", `${base}^{commit}`], { cwd: root })
  if (ref.exitCode !== 0) throw new Error(`invalid git diff base: ${base}`)
  const sha = decoder.decode(ref.stdout).trim()
  const diff = Bun.spawnSync(["git", "diff", "--name-only", "--diff-filter=ACMR", "-z", sha, "--", "test", "src"], { cwd: root })
  const extra = Bun.spawnSync(["git", "ls-files", "--others", "--exclude-standard", "-z", "--", "test", "src"], { cwd: root })
  if (diff.exitCode !== 0 || extra.exitCode !== 0) throw new Error("git diff failed")
  return [...new Set(`${decoder.decode(diff.stdout)}${decoder.decode(extra.stdout)}`
    .split("\0")
    .filter(file => /^(?:test|src)\/.*\.test\.tsx?$/.test(file)))]
    .sort()
}

const args = Bun.argv.slice(2)
const cwd = process.cwd()
const delta = args[0] === "--changed"
const strict = delta || args[0] === "--strict"
if (delta && !args[1]) {
  console.error("check-tests: --changed requires an explicit git diff base")
  process.exit(2)
}
if ((!strict && args.length > 0) || (delta && args.length !== 2) || (strict && !delta && args.length !== 1)) {
  console.error("check-tests: usage: bun scripts/check-tests.ts [--strict | --changed <base>]")
  process.exit(2)
}

try {
  const files = delta ? changed(cwd, args[1]) : full(cwd)
  const hits = (await Promise.all(files.map(file => scan(cwd, file))))
    .flat()
    .sort((a, b) => a.path.localeCompare(b.path) || a.line - b.line || a.text.localeCompare(b.text))
  hits.forEach(hit => console.error(`${hit.path}:${hit.line}: ${hit.text}`))
  if (strict && hits.length > 0) process.exit(1)
} catch (err) {
  console.error(`check-tests: ${err instanceof Error ? err.message : String(err)}`)
  process.exit(2)
}
